---
# tasks file for swygue-backuppc-client

- name: check for BackupPC server
  package:
    name: BackupPC
    state: present
  check_mode: true
  register: is_installed

- name: fail if this is not a BackupPC server
  fail:
    msg: "This system does not appear to be a BackupPC server. Please check your play host and try again."
  when: is_installed.changed

- name: ensure backup client shortname is in backuppc server known host
  lineinfile:
    dest: /etc/ssh/ssh_known_hosts
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa {{ item.shortname }}') }}"
    #line: "{{ lookup('pipe', 'ssh-keyscan -t Ed25519 {{ item.shortname }}') }}"
    regexp: "^{{ item.shortname }}"
    create: yes
    group: root
    owner: root
    mode: u=rw,g=r,o=r
  with_items: "{{ backuppc_hosts }}"
  when: item.state is not defined or item.state == 'present' and item.shortname is defined
  tags: add-to-host

- name: ensure backup client hostname is in backuppc server known host
  lineinfile:
    dest: /etc/ssh/ssh_known_hosts
    state: present
    #line: "{{ lookup('pipe', 'ssh-keyscan -t Ed25519 {{ item.hostname }}') }}"
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa {{ item.hostname }}') }}"
    regexp: "^{{ item.hostname }}"
    create: yes
    group: root
    owner: root
    mode: u=rw,g=r,o=r
  with_items: "{{ backuppc_hosts }}"
  when: item.state is not defined or item.state == 'present' and item.hostname is defined
  tags: add-to-host

- name: TEMPLATE | Put host specific config on BackupPC server
  template:
    src: backuppc_host.pl.j2
    dest: '/etc/BackupPC/pc/{{ item.shortname }}.pl'
    owner: backuppc
    group: apache
    mode: 0644
  with_items: "{{ backuppc_hosts }}"
  when: item.state is not defined or item.state == 'present'
  notify: restart backuppc

- name: LINEINFILE | Add host to BackupPC server
  lineinfile: >
    dest=/etc/BackupPC/hosts
    line="{{ item.shortname }}\t0\tbackuppc"
    regexp="^{{ item.shortname }}"
    state={{ item.state if item.state is defined else 'present' }}
  with_items: "{{ backuppc_hosts }}"
  notify: restart backuppc

