---
# tasks file for swygue-backuppc

- name: ensure rsync and libselinux-python is installed
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - rsync
    - libselinux-python

- name: add backuppc ssh authorized_keys
  authorized_key:
    user: "{{ backuppc_client_user }}"
    key: "{{ backuppc_ssh_key }}"
    state: present

- name: ensure /usr/local/bin/add-known-host exists
  copy:
    src: add-known-host
    dest: /usr/local/bin/add-known-host
    mode: u+rwx,g+rx,o+rx
    owner: root
    group: root

- name: ensure backup client is in backuppc server known host
  script: "/usr/local/bin/add-known-host -u root -h {{ item.alias }},{{ item.hostname }}"
  register: is_known_host
  changed_when: is_known_host.stdout == 'UPDATED'

- name: TEMPLATE | Put host specific config on BackupPC server
  template:
    src: "{{ backuppc_host_template|default('backuppc_host.pl.j2') }}"
    dest: '/etc/BackupPC/pc/{{ item.alias }}.pl'
    owner: backuppc
    group: apache
    mode: 0644
  when: item.state is not defined or item.state == 'present'
  with_items: "{{ backuppc_hosts }}"
  notify: restart backuppc
  delegate_to: "{{ backuppc_server }}"
  register: is_host_template
  until: is_host_template is succeeded
  retries: 3
  delay: 1
  ignore_errors: yes
  run_once: true

- name: LINEINFILE | Add host to BackupPC server
  lineinfile: >
    dest=/etc/BackupPC/hosts
    line="{{ item.alias }}\t0\tbackuppc"
    regexp="^{{ item.alias }}"
    state={{ item.state if item.state is defined else 'present' }}
  with_items: "{{ backuppc_hosts }}"
  delegate_to: "{{ backuppc_server }}"
  register: is_config_updated
  until: is_config_updated is succeeded
  retries: 3
  delay: 1
  ignore_errors: yes
  run_once: true
