---
# tasks file for swygue-backuppc

- name: ensure rsync and libselinux-python is installed
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - rsync
    - libselinux-python

- name: is backup host available
  wait_for:
    host: "{{ backuppc_server }}"
    port: 22
    state: started
    timeout: 1
  register: backup_host_status
  ignore_errors: yes
  connection:

- debug: msg="{{ backuppc_server }} is not available"
  when: backup_host_status.failed

- name: add host to BackupPC server
  include_tasks: add.yml
  when: not backup_host_status.failed
