#!/bin/bash

if [ $# -lt 2 ]
then
  echo "Usage: $0 -h -u"
  echo "-h host or command separated list of hosts"
  echo "-u ssh user"
fi

while getopts h:u: opt
do
  case $opt in 
    h) HOSTS=$OPTARG;;
    u) USER=$OPTARG;;
  esac
done


FILE=~/.ssh/known_hosts

OIFS=$IFS
IFS=','
for host in $HOSTS;
do
    KEY=$(ssh -o StrictHostKeyChecking=yes -o "BatchMode=yes" $USER@$host 'exit' 2>&1 | grep "Offending" | cut -d: -f2 |  tr -d "\r" | sort -nr | xargs echo)

    if [ "A${KEY}" != "A" ];
    then
         IFS=$OIFS
         for i in $(echo $KEY);
         do
            echo "Deleting $host offending key"
            sed -i "${i}d" $FILE
            OFFEND=UPDATED
         done
         IFS=','
    fi

    # This will add host-key if it's missing
    ADD_KEY=$(ssh -o StrictHostKeyChecking=no -o "BatchMode=yes" $USER@$host 'exit' 2>&1 | grep 'Permanently added'|awk '{print $2}')

    if [ "${ADD_KEY}" == "Permanently" ];
    then
         ADDED=UPDATED
    fi
      
done

# Return STDOUT
if [ "$ADDED" == "UPDATED" ] || [ "$OFFEND" == "UPDATED" ];
then
     echo UPDATED
else
     echo NOCHANGE
fi

exit 0